/*
 * License
 * This software is distributed under the license  * 
 * Open to modification and redistribution * 
 */
package ui;

/**
 *
 * @author rober
 */
public class AddCropCategory extends javax.swing.JFrame {

    /**
     * Creates new form addCropCategory
     */
    public AddCropCategory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        footerPanel = new javax.swing.JPanel();
        mainTitle = new javax.swing.JLabel();
        cropCategoryDataPanel = new javax.swing.JPanel();
        cropCategoryDataHeading = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        cropCoefficientLabel = new javax.swing.JLabel();
        cropCategoryLabel = new javax.swing.JLabel();
        cropRootDepthLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cropCategory = new javax.swing.JTextField();
        cropCoefficient = new javax.swing.JTextField();
        cropRootDepth = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1139, 585));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setForeground(new java.awt.Color(0, 0, 0));

        footerPanel.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        mainTitle.setBackground(new java.awt.Color(255, 255, 255));
        mainTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(0, 0, 0));
        mainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitle.setText("Create a New Crop Category");

        cropCategoryDataPanel.setBackground(new java.awt.Color(255, 255, 255));
        cropCategoryDataPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 2, true));
        cropCategoryDataPanel.setForeground(new java.awt.Color(0, 0, 0));

        cropCategoryDataHeading.setBackground(new java.awt.Color(0, 51, 51));
        cropCategoryDataHeading.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 2, true));

        headingLabel.setBackground(new java.awt.Color(0, 51, 51));
        headingLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(255, 255, 255));
        headingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel.setText("Enter the new Crop Category Data and click Save");

        javax.swing.GroupLayout cropCategoryDataHeadingLayout = new javax.swing.GroupLayout(cropCategoryDataHeading);
        cropCategoryDataHeading.setLayout(cropCategoryDataHeadingLayout);
        cropCategoryDataHeadingLayout.setHorizontalGroup(
            cropCategoryDataHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cropCategoryDataHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cropCategoryDataHeadingLayout.setVerticalGroup(
            cropCategoryDataHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cropCategoryDataHeadingLayout.createSequentialGroup()
                .addComponent(headingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        cropCoefficientLabel.setBackground(new java.awt.Color(255, 255, 255));
        cropCoefficientLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cropCoefficientLabel.setForeground(new java.awt.Color(0, 0, 0));
        cropCoefficientLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cropCoefficientLabel.setText("Average Crop Coefficient :");

        cropCategoryLabel.setBackground(new java.awt.Color(255, 255, 255));
        cropCategoryLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cropCategoryLabel.setForeground(new java.awt.Color(0, 0, 0));
        cropCategoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cropCategoryLabel.setText("Crop Category Name :");

        cropRootDepthLabel.setBackground(new java.awt.Color(255, 255, 255));
        cropRootDepthLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cropRootDepthLabel.setForeground(new java.awt.Color(0, 0, 0));
        cropRootDepthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cropRootDepthLabel.setText("Average Root Depth :");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));

        cropCategory.setBackground(new java.awt.Color(255, 255, 255));
        cropCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cropCategory.setForeground(new java.awt.Color(0, 0, 0));
        cropCategory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 1, true));

        cropCoefficient.setBackground(new java.awt.Color(255, 255, 255));
        cropCoefficient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cropCoefficient.setForeground(new java.awt.Color(0, 0, 0));
        cropCoefficient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 1, true));

        cropRootDepth.setBackground(new java.awt.Color(255, 255, 255));
        cropRootDepth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cropRootDepth.setForeground(new java.awt.Color(0, 0, 0));
        cropRootDepth.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 1, true));

        saveButton.setBackground(new java.awt.Color(0, 51, 51));
        saveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveButton.setForeground(new java.awt.Color(0, 0, 0));
        saveButton.setText("Save");

        backButton.setBackground(new java.awt.Color(0, 51, 51));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 0, 0));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cropCategoryDataPanelLayout = new javax.swing.GroupLayout(cropCategoryDataPanel);
        cropCategoryDataPanel.setLayout(cropCategoryDataPanelLayout);
        cropCategoryDataPanelLayout.setHorizontalGroup(
            cropCategoryDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cropCategoryDataHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cropCategoryDataPanelLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addGroup(cropCategoryDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cropCategoryDataPanelLayout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cropCategoryDataPanelLayout.createSequentialGroup()
                        .addGroup(cropCategoryDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cropRootDepthLabel)
                            .addComponent(cropCoefficientLabel)
                            .addComponent(cropCategoryLabel))
                        .addGap(93, 93, 93)
                        .addGroup(cropCategoryDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cropCategory)
                            .addComponent(cropCoefficient)
                            .addComponent(cropRootDepth))
                        .addGap(135, 135, 135)))
                .addGap(71, 71, 71))
        );
        cropCategoryDataPanelLayout.setVerticalGroup(
            cropCategoryDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cropCategoryDataPanelLayout.createSequentialGroup()
                .addComponent(cropCategoryDataHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(cropCategoryDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cropCategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cropCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(cropCategoryDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cropRootDepthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cropRootDepth, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(cropCategoryDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cropCoefficientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cropCoefficient, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addGroup(cropCategoryDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(backButton))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(412, 412, 412)
                .addComponent(mainTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(435, 435, 435))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(cropCategoryDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addComponent(mainTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cropCategoryDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1103, 581));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        
        //check if user entered some data
        //warn the user that he/she will loose the already entered data
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCropCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCropCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCropCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCropCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCropCategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField cropCategory;
    private javax.swing.JPanel cropCategoryDataHeading;
    private javax.swing.JPanel cropCategoryDataPanel;
    private javax.swing.JLabel cropCategoryLabel;
    private javax.swing.JTextField cropCoefficient;
    private javax.swing.JLabel cropCoefficientLabel;
    private javax.swing.JTextField cropRootDepth;
    private javax.swing.JLabel cropRootDepthLabel;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
