/*
 * License
 * This software is distributed under the license  * 
 * Open to modification and redistribution * 
 */
package ui;

/**
 *
 * @author rober
 */
public class ChooseCrop extends javax.swing.JFrame {

    /**
     * Creates new form ChooseCrop
     */
    public ChooseCrop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        climateAndPET = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        footerPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        climateAndPETPanel = new javax.swing.JPanel();
        climateAndPETHeader = new javax.swing.JPanel();
        climateAndPETLabel = new javax.swing.JLabel();
        coolHumidPET = new javax.swing.JRadioButton();
        coolDryPET = new javax.swing.JRadioButton();
        warmHumidPET = new javax.swing.JRadioButton();
        warmDryPET = new javax.swing.JRadioButton();
        hotHumidPET = new javax.swing.JRadioButton();
        hotDryPET = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        chooseCropPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        chooseCropLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setForeground(new java.awt.Color(0, 51, 51));

        footerPanel.setBackground(new java.awt.Color(0, 51, 51));
        footerPanel.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jSeparator1.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        climateAndPETPanel.setBackground(new java.awt.Color(255, 255, 255));
        climateAndPETPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));
        climateAndPETPanel.setForeground(new java.awt.Color(0, 0, 0));

        climateAndPETHeader.setBackground(new java.awt.Color(0, 51, 51));
        climateAndPETHeader.setForeground(new java.awt.Color(255, 255, 255));

        climateAndPETLabel.setBackground(new java.awt.Color(0, 51, 51));
        climateAndPETLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        climateAndPETLabel.setForeground(new java.awt.Color(255, 255, 255));
        climateAndPETLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        climateAndPETLabel.setText("Climate and PET");

        javax.swing.GroupLayout climateAndPETHeaderLayout = new javax.swing.GroupLayout(climateAndPETHeader);
        climateAndPETHeader.setLayout(climateAndPETHeaderLayout);
        climateAndPETHeaderLayout.setHorizontalGroup(
            climateAndPETHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(climateAndPETHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(climateAndPETLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        climateAndPETHeaderLayout.setVerticalGroup(
            climateAndPETHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(climateAndPETLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        coolHumidPET.setBackground(new java.awt.Color(255, 255, 255));
        climateAndPET.add(coolHumidPET);
        coolHumidPET.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        coolHumidPET.setForeground(new java.awt.Color(0, 0, 0));
        coolHumidPET.setText("Cool Humid");
        coolHumidPET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coolHumidPETActionPerformed(evt);
            }
        });

        coolDryPET.setBackground(new java.awt.Color(255, 255, 255));
        climateAndPET.add(coolDryPET);
        coolDryPET.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        coolDryPET.setForeground(new java.awt.Color(0, 0, 0));
        coolDryPET.setText("Cool Dry");
        coolDryPET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coolDryPETActionPerformed(evt);
            }
        });

        warmHumidPET.setBackground(new java.awt.Color(255, 255, 255));
        climateAndPET.add(warmHumidPET);
        warmHumidPET.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        warmHumidPET.setForeground(new java.awt.Color(0, 0, 0));
        warmHumidPET.setText("Warm Humid");
        warmHumidPET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warmHumidPETActionPerformed(evt);
            }
        });

        warmDryPET.setBackground(new java.awt.Color(255, 255, 255));
        climateAndPET.add(warmDryPET);
        warmDryPET.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        warmDryPET.setForeground(new java.awt.Color(0, 0, 0));
        warmDryPET.setText("Warm Dry");
        warmDryPET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warmDryPETActionPerformed(evt);
            }
        });

        hotHumidPET.setBackground(new java.awt.Color(255, 255, 255));
        climateAndPET.add(hotHumidPET);
        hotHumidPET.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hotHumidPET.setForeground(new java.awt.Color(0, 0, 0));
        hotHumidPET.setText("Hot Humid");
        hotHumidPET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotHumidPETActionPerformed(evt);
            }
        });

        hotDryPET.setBackground(new java.awt.Color(255, 255, 255));
        climateAndPET.add(hotDryPET);
        hotDryPET.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hotDryPET.setForeground(new java.awt.Color(0, 0, 0));
        hotDryPET.setText("Hot Dry");
        hotDryPET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotDryPETActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("WARM");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("HOT");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("COOL");

        jSeparator2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Humid");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Dry");

        javax.swing.GroupLayout climateAndPETPanelLayout = new javax.swing.GroupLayout(climateAndPETPanel);
        climateAndPETPanel.setLayout(climateAndPETPanelLayout);
        climateAndPETPanelLayout.setHorizontalGroup(
            climateAndPETPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(climateAndPETHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, climateAndPETPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(climateAndPETPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(climateAndPETPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21)))
                .addGap(18, 18, 18)
                .addGroup(climateAndPETPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(climateAndPETPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(142, 142, 142)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49))
                    .addGroup(climateAndPETPanelLayout.createSequentialGroup()
                        .addGroup(climateAndPETPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coolHumidPET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(climateAndPETPanelLayout.createSequentialGroup()
                                .addComponent(coolDryPET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(4, 4, 4)))
                        .addGap(32, 32, 32)
                        .addGroup(climateAndPETPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(warmHumidPET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(climateAndPETPanelLayout.createSequentialGroup()
                                .addComponent(warmDryPET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6)))
                        .addGap(40, 40, 40)
                        .addGroup(climateAndPETPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(climateAndPETPanelLayout.createSequentialGroup()
                                .addComponent(hotDryPET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(21, 21, 21))
                            .addComponent(hotHumidPET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(55, 55, 55))
        );
        climateAndPETPanelLayout.setVerticalGroup(
            climateAndPETPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(climateAndPETPanelLayout.createSequentialGroup()
                .addComponent(climateAndPETHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(climateAndPETPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addGroup(climateAndPETPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(climateAndPETPanelLayout.createSequentialGroup()
                        .addGroup(climateAndPETPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hotHumidPET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(coolHumidPET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(warmHumidPET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(climateAndPETPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coolDryPET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hotDryPET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(warmDryPET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(climateAndPETPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(climateAndPETPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(48, 48, 48)))
                .addGap(62, 62, 62))
        );

        chooseCropPanel.setBackground(new java.awt.Color(255, 255, 255));
        chooseCropPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));
        chooseCropPanel.setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        chooseCropLabel.setBackground(new java.awt.Color(0, 51, 51));
        chooseCropLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chooseCropLabel.setForeground(new java.awt.Color(255, 255, 255));
        chooseCropLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chooseCropLabel.setText("Choose the Crop to Grow");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chooseCropLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chooseCropLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout chooseCropPanelLayout = new javax.swing.GroupLayout(chooseCropPanel);
        chooseCropPanel.setLayout(chooseCropPanelLayout);
        chooseCropPanelLayout.setHorizontalGroup(
            chooseCropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(chooseCropPanelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        chooseCropPanelLayout.setVerticalGroup(
            chooseCropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseCropPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47)
                .addComponent(jComboBox1)
                .addGap(126, 126, 126))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chooseCropPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(climateAndPETPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(534, 534, 534))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(climateAndPETPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chooseCropPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coolHumidPETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coolHumidPETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coolHumidPETActionPerformed

    private void coolDryPETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coolDryPETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coolDryPETActionPerformed

    private void warmHumidPETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warmHumidPETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warmHumidPETActionPerformed

    private void warmDryPETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warmDryPETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warmDryPETActionPerformed

    private void hotHumidPETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotHumidPETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotHumidPETActionPerformed

    private void hotDryPETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotDryPETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotDryPETActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseCrop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseCrop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseCrop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseCrop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseCrop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chooseCropLabel;
    private javax.swing.JPanel chooseCropPanel;
    private javax.swing.ButtonGroup climateAndPET;
    private javax.swing.JPanel climateAndPETHeader;
    private javax.swing.JLabel climateAndPETLabel;
    private javax.swing.JPanel climateAndPETPanel;
    private javax.swing.JPanel climatePETForm;
    private javax.swing.JPanel climatePETForm1;
    private javax.swing.JPanel climatePETForm2;
    private javax.swing.JPanel climatePETForm3;
    private javax.swing.JPanel climatePETFormHeadr;
    private javax.swing.JPanel climatePETFormHeadr1;
    private javax.swing.JPanel climatePETFormHeadr2;
    private javax.swing.JPanel climatePETFormHeadr3;
    private javax.swing.JLabel climatePETLable;
    private javax.swing.JLabel climatePETLable1;
    private javax.swing.JLabel climatePETLable2;
    private javax.swing.JLabel climatePETLable3;
    private javax.swing.JRadioButton coolDryPET;
    private javax.swing.JRadioButton coolHumidPET;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JRadioButton hotDryPET;
    private javax.swing.JRadioButton hotHumidPET;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton warmDryPET;
    private javax.swing.JRadioButton warmHumidPET;
    // End of variables declaration//GEN-END:variables
}
