/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

/**
 *
 * @author rober
 */
public class Dashboard extends javax.swing.JFrame {

    /** Creates new form Dashboard */
    public Dashboard() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        MainSystemLabel = new javax.swing.JLabel();
        configureDripTab = new javax.swing.JTabbedPane();
        welcomeTab = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        CcreateTab = new javax.swing.JPanel();
        updateTab = new javax.swing.JPanel();
        descriptionsTab = new javax.swing.JPanel();
        usersTab = new javax.swing.JPanel();
        footeCopyright = new javax.swing.JLabel();
        footerYear = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        fileExit = new javax.swing.JMenuItem();
        createMenu = new javax.swing.JMenu();
        addSoilType = new javax.swing.JMenuItem();
        addCropType = new javax.swing.JMenuItem();
        addEmitterType = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        printMenu = new javax.swing.JMenu();
        printDripSysInfo = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Dashboard");
        setBackground(new java.awt.Color(0, 51, 51));

        MainPanel.setBackground(new java.awt.Color(0, 51, 51));

        MainSystemLabel.setBackground(new java.awt.Color(0, 51, 51));
        MainSystemLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MainSystemLabel.setForeground(new java.awt.Color(255, 255, 255));
        MainSystemLabel.setText("DripIrri Manager");

        configureDripTab.setBackground(new java.awt.Color(0, 51, 51));
        configureDripTab.setForeground(new java.awt.Color(255, 255, 255));
        configureDripTab.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        configureDripTab.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        configureDripTab.setName(""); // NOI18N
        configureDripTab.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout welcomeTabLayout = new javax.swing.GroupLayout(welcomeTab);
        welcomeTab.setLayout(welcomeTabLayout);
        welcomeTabLayout.setHorizontalGroup(
            welcomeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1185, Short.MAX_VALUE)
        );
        welcomeTabLayout.setVerticalGroup(
            welcomeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        configureDripTab.addTab("Welcome", welcomeTab);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1185, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        configureDripTab.addTab("Configure drip", jPanel1);

        javax.swing.GroupLayout CcreateTabLayout = new javax.swing.GroupLayout(CcreateTab);
        CcreateTab.setLayout(CcreateTabLayout);
        CcreateTabLayout.setHorizontalGroup(
            CcreateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1185, Short.MAX_VALUE)
        );
        CcreateTabLayout.setVerticalGroup(
            CcreateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        configureDripTab.addTab("Create", CcreateTab);

        javax.swing.GroupLayout updateTabLayout = new javax.swing.GroupLayout(updateTab);
        updateTab.setLayout(updateTabLayout);
        updateTabLayout.setHorizontalGroup(
            updateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1185, Short.MAX_VALUE)
        );
        updateTabLayout.setVerticalGroup(
            updateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        configureDripTab.addTab("Update", updateTab);

        javax.swing.GroupLayout descriptionsTabLayout = new javax.swing.GroupLayout(descriptionsTab);
        descriptionsTab.setLayout(descriptionsTabLayout);
        descriptionsTabLayout.setHorizontalGroup(
            descriptionsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1185, Short.MAX_VALUE)
        );
        descriptionsTabLayout.setVerticalGroup(
            descriptionsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        configureDripTab.addTab("Description", descriptionsTab);

        javax.swing.GroupLayout usersTabLayout = new javax.swing.GroupLayout(usersTab);
        usersTab.setLayout(usersTabLayout);
        usersTabLayout.setHorizontalGroup(
            usersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1185, Short.MAX_VALUE)
        );
        usersTabLayout.setVerticalGroup(
            usersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        configureDripTab.addTab("Users", usersTab);

        footeCopyright.setText("copyright");

        footerYear.setBackground(new java.awt.Color(0, 51, 51));
        footerYear.setForeground(new java.awt.Color(255, 255, 255));
        footerYear.setText("year");
        footerYear.setBorder(null);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(configureDripTab)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(451, 451, 451)
                                .addComponent(MainSystemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(566, 566, 566)
                                .addComponent(footeCopyright)
                                .addGap(18, 18, 18)
                                .addComponent(footerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(MainSystemLabel)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(configureDripTab, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(footerYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(footeCopyright))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setAutoscrolls(true);

        jMenu1.setText("File");

        fileExit.setText("Exit");
        jMenu1.add(fileExit);

        jMenuBar1.add(jMenu1);

        createMenu.setText("Create");

        addSoilType.setText("Add New Soil Type");
        createMenu.add(addSoilType);

        addCropType.setText("Add New Crop");
        createMenu.add(addCropType);

        addEmitterType.setText("Add New Emitter");
        createMenu.add(addEmitterType);

        jMenuBar1.add(createMenu);

        editMenu.setText("Edit");
        jMenuBar1.add(editMenu);

        printMenu.setText("Print");

        printDripSysInfo.setText("Print Drip System Information");
        printMenu.add(printDripSysInfo);

        jMenuBar1.add(printMenu);

        helpMenu.setText("Help");
        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CcreateTab;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel MainSystemLabel;
    private javax.swing.JMenuItem addCropType;
    private javax.swing.JMenuItem addEmitterType;
    private javax.swing.JMenuItem addSoilType;
    private javax.swing.JTabbedPane configureDripTab;
    private javax.swing.JMenu createMenu;
    private javax.swing.JPanel descriptionsTab;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem fileExit;
    private javax.swing.JLabel footeCopyright;
    private javax.swing.JTextField footerYear;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem printDripSysInfo;
    private javax.swing.JMenu printMenu;
    private javax.swing.JPanel updateTab;
    private javax.swing.JPanel usersTab;
    private javax.swing.JPanel welcomeTab;
    // End of variables declaration//GEN-END:variables

}
